export const PEIData = [
  {
    pb_id: '10014-49',
    swift_client_number: '0008013137',
    swift_client_name: '3I GROUP PLC',
    gmdm_id: '11111111',
    dgmf_id: '11111112',
    duns_number: '211984430',
    view_type: 'Complete',
    tableau_inclusion_status: 'Include',
    requested_by_team: 'MA',
    contact_email: 'dummy@dummy.com',
    priority_for_feedback: 'None',
    fy_period_added: 'FY24 P01',
    reporting_team: 'MA',
    gmdm_legal_name: '3I GROUP PLC',
    pb_name: '3I GROUP PLC',
    sources: 'https://google.com'
  },
  {
    pb_id: '10035-46',
    swift_client_number: '0008013887',
    swift_client_name: 'ABRY PARTNERS, INC.',
    gmdm_id: '11111113',
    dgmf_id: '11111114',
    duns_number: '961613353',
    view_type: 'Lighter',
    tableau_inclusion_status: 'Include',
    requested_by_team: 'MA',
    contact_email: 'dummy@dummy.com',
    priority_for_feedback: 'None',
    fy_period_added: 'FY24 P01',
    reporting_team: 'MA',
    gmdm_legal_name: 'ABRY PARTNERS, INC.',
    pb_name: 'ABRY PARTNERS, INC.',
    sources: 'https://google.com'
  },
  {
    pb_id: '10041-85',
    swift_client_number: '0008003245',
    swift_client_name: 'ACCESS INDUSTRIES, INC.',
    gmdm_id: '11111113',
    dgmf_id: '11111114',
    duns_number: '867705584',
    view_type: 'Complete',
    tableau_inclusion_status: 'Include',
    requested_by_team: 'MA',
    contact_email: 'dummy@dummy.com',
    priority_for_feedback: 'None',
    fy_period_added: 'FY24 P01',
    reporting_team: 'MA',
    gmdm_legal_name: 'ACCESS INDUSTRIES, INC.',
    pb_name: 'ACCESS INDUSTRIES, INC.',
    sources: 'https://google.com'
  },
  {
    pb_id: '10055-98',
    swift_client_number: '0008008701',
    swift_client_name: 'ACON INVESTMENTS, L.L.C.',
    gmdm_id: '11111113',
    dgmf_id: '11111114',
    duns_number: '933720823',
    view_type: 'Lighter',
    tableau_inclusion_status: 'Include',
    requested_by_team: 'MA',
    contact_email: 'dummy@dummy.com',
    priority_for_feedback: 'None',
    fy_period_added: 'FY24 P01',
    reporting_team: 'MA',
    gmdm_legal_name: 'ACON INVESTMENTS, L.L.C.',
    pb_name: 'ACON INVESTMENTS, L.L.C.',
    sources: 'https://google.com'
  },
  {
    pb_id: '10061-29',
    swift_client_number: '0008013683',
    swift_client_name: 'ADVENT INTERNATIONAL CORPORATI',
    gmdm_id: '11111113',
    dgmf_id: '11111114',
    duns_number: '130850480',
    view_type: 'Complete',
    tableau_inclusion_status: 'Include',
    requested_by_team: 'MA',
    contact_email: 'dummy@dummy.com',
    priority_for_feedback: 'None',
    fy_period_added: 'FY24 P01',
    reporting_team: 'MA',
    gmdm_legal_name: 'ADVENT INTERNATIONAL CORPORATI',
    pb_name: 'ADVENT INTERNATIONAL CORPORATI',
    sources: 'https://google.com'
  },
  {
    pb_id: '101726-65',
    swift_client_number: '0008001997',
    swift_client_name: 'AEA INVESTORS LP',
    gmdm_id: '11111113',
    dgmf_id: '11111114',
    duns_number: '048352355',
    view_type: 'Lighter',
    tableau_inclusion_status: 'Include',
    requested_by_team: 'MA',
    contact_email: 'dummy@dummy.com',
    priority_for_feedback: 'None',
    fy_period_added: 'FY24 P01',
    reporting_team: 'MA',
    gmdm_legal_name: 'AEA INVESTORS LP',
    pb_name: 'AEA INVESTORS LP',
    sources: 'https://google.com'
  },
  {
    pb_id: '10173-25',
    swift_client_number: '0008010096',
    swift_client_name: 'AIG HIGHSTAR CAPITAL, L.P.',
    gmdm_id: '11111113',
    dgmf_id: '11111114',
    duns_number: '132092326',
    view_type: 'Complete',
    tableau_inclusion_status: 'Include',
    requested_by_team: 'MA',
    contact_email: 'dummy@dummy.com',
    priority_for_feedback: 'None',
    fy_period_added: 'FY24 P01',
    reporting_team: 'MA',
    gmdm_legal_name: 'AIG HIGHSTAR CAPITAL, L.P.',
    pb_name: 'AIG HIGHSTAR CAPITAL, L.P.',
    sources: 'https://google.com'
  },
  {
    pb_id: '101954-80',
    swift_client_number: '0008005974',
    swift_client_name: 'ALINDA CAPITAL PARTNERS LLC',
    gmdm_id: '11111113',
    dgmf_id: '11111114',
    duns_number: '608469362',
    view_type: 'Lighter',
    tableau_inclusion_status: 'Include',
    requested_by_team: 'MA',
    contact_email: 'dummy@dummy.com',
    priority_for_feedback: 'None',
    fy_period_added: 'FY24 P01',
    reporting_team: 'MA',
    gmdm_legal_name: 'ALINDA CAPITAL PARTNERS LLC',
    pb_name: 'ALINDA CAPITAL PARTNERS LLC',
    sources: 'https://google.com'
  },
  {
    pb_id: '10204-66',
    swift_client_number: '0008022747',
    swift_client_name: 'ALPINE INVESTORS, LP',
    gmdm_id: '11111113',
    dgmf_id: '11111114',
    duns_number: '019791957',
    view_type: 'Lighter',
    tableau_inclusion_status: 'Include',
    requested_by_team: 'MA',
    contact_email: 'dummy@dummy.com',
    priority_for_feedback: 'None',
    fy_period_added: 'FY24 P01',
    reporting_team: 'MA',
    gmdm_legal_name: 'ALPINE INVESTORS, LP',
    pb_name: 'ALPINE INVESTORS, LP',
    sources: 'https://google.com'
  },
  {
    pb_id: '10204-66',
    swift_client_number: '0008018028',
    swift_client_name: 'ALTAMONT CAPITAL PARTNERS LLC',
    gmdm_id: '11111113',
    dgmf_id: '11111114',
    duns_number: '078606403',
    view_type: 'Lighter',
    tableau_inclusion_status: 'Include',
    requested_by_team: 'MA',
    contact_email: 'dummy@dummy.com',
    priority_for_feedback: 'None',
    fy_period_added: 'FY24 P01',
    reporting_team: 'MA',
    gmdm_legal_name: 'ALTAMONT CAPITAL PARTNERS LLC',
    pb_name: 'ALTAMONT CAPITAL PARTNERS LLC',
    sources: 'https://google.com'
  }
]
